Update compliance.yml to use latest version of SDL tasks
xamarin/Merq pull request #23
Opened 2022-11-17 19:03 UTC by japarson

- Update compliance.yml to use latest version of SDL tasks.
- Configure TSA logs to not be uploaded unless source branch is main.

2022-11-17 19:24 UTC, mariaghiondea approved these changes

2022-11-17 19:56 UTC, emaf requested changes

2022-11-17 19:56 UTC, emaf commented on build/stages/compliance.yml
> +      ProductId: '$(System.TeamProjectId)'
ProductId is incorrectly indented and that breaks the pipeline (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6979387&view=results)

2022-11-18 23:04 UTC, emaf approved these changes

2022-11-18 23:08 UTC, merged